

const broad_areas = [
  "Admission Prep - SOP(In India)",
  "Admission Prep - SOP(Outside India)",
  "Core engineering paths (leading into narrow areas of expertise)",
  "Course/electives selection",
  "Exam Prep - CAT, Others(In India)",
  "Exam Prep - GMAT, GRE, Others(Outside India)",
  "Finding Jobs/Internships",
  "In-school projects",
  "Non-engineering career paths/success stories",
  "Professional ( MBA in India)",
  "Professional ( MBA outside India)",
  "Professional (Masters in India)",
  "Professional (Masters outside India)",
  "Research (Masters/Ph.D in India)",
  "Research (Masters/Ph.D outside India)",
  "Resume/Interview Prep",
  "Startups/Entrepreneurship",
  "Technical skills training (eg: industry best practices, coding skills etc.)",
  "Other"
];

const narrow_areas = [
  "Building Science/Technology -- Architecture",
  "Construction Methods/Materials -- Architecture",
  "Construction Science/Technology -- Architecture",
  "Critical History -- Architecture",
  "Design Theory -- Architecture",
  "Industrial Design -- Architecture",
  "Product Design -- Architecture",
  "Historic Conservation/Preservation -- Architecture",
  "Urban Planning -- Architecture",
  "Urban Planning/Design -- Architecture",
  "Finance -- Management",
  "Strategy -- Management",
  "Operations -- Management",
  "Human Resources(HR) -- Management",
  "Project Management -- Management",
  "Climate change and sustainability -- Miscellaneous topics",
  "Non-profits -- Miscellaneous topics",
  "Public policy",
  "Construction management -- Civil Engg",
  "Green Technologies -- Material Science",
  "Energy Management -- Mech Engg, Prod Engg",
  "Green buildings",
  "Stem cell therapy -- Biotechnology",
  "Tissue engineering -- Biotechnology",
  "Bioengineering -- Chemical Engg",
  "Artificial Intelligence, Machine Learning, Data Science -- CSE EEE ECE",
  "Management Consulting -- Management",
  "Product Management -- Management",
  "Data Science & Analytics -- Mech Engg, Prod Engg",
  "Fluid Mechanics -- Chemical Engg",
  "Process Control -- Chemical Engg",
  "Marketing -- Management",
  "Startups/Small Business -- Management",
  "Organization Development & Change Management -- Mech Engg, Prod Engg",
  "Materials Science -- Chemical Engg",
  "Electrochemistry -- Chemical Engg",
  "Surface Science -- Chemical Engg",
  "Battery technology",
  "Energy Storage",
  "Nanomaterials",
  "2D materials",
  "Machine Learning for Process Control -- Chemical Engg",
  "Membranes and Separations -- Chemical Engg",
  "Catalysis -- Chemical Engg",
  "Polymer Science -- Chemical Engg",
  "Reaction Engineering -- Chemical Engg",
  "Machine Learning for Polymer Science -- Chemical Engg",
  "Environmental Science -- Chemical Engg",
  "Algebra -- Mathematics",
  "Probability and statistics -- Mathematics",
  "Logic -- Mathematics",
  "Oil and Gas",
  "Peteoleum",
  "Process Design",
  "Molecular Simulations -- Chemical Engg",
  "Statistical Mechanics -- Chemical Engg",
  "Biophysics -- Chemical Engg",
  "Biochemistry -- Chemical Engg",
  "Enviromental engineering -- Civil Engg",
  "Soil mechanics and Foundation Engineering -- Civil Engg",
  "Materials/Pavements -- Civil Engg",
  "Structural Engineering -- Civil Engg",
  "Geotechnical engineering -- Civil Engg",
  "Transportation Engineering -- Civil Engg",
  "Water Resources Engineering -- Civil Engg",
  "Hydraulics -- Civil Engg",
  "BIM",
  "Applied Statistics -- Civil Engg",
  "Safety Engineering -- Civil Engg",
  "geographic information systems (GIS) -- Civil Engg",
  "Geology -- Civil Engg",
  "Computational mechanics -- Civil Engg",
  "Earthquake engineering -- Civil Engg",
  "Coastal/Ocean Engineering -- Civil Engg",
  "Data Science/Analytics -- Civil Engg",
  "Structural Dynamics -- Civil Engg",
  "Systems Engineering -- Civil Engg",
  "Tunnel Engineering -- Civil Engg",
  "Aerospace Structures/Aerodynamics -- Civil Engg",
  "Industry softwares",
  "Computer Architecture, Operating Systems -- CSE EEE ECE",
  "Web development",
  "coding",
  "Geophysics -- Engg Phy",
  "Software Engineering",
  "Coding",
  "Channel Sales/Distribution/Retail/Logistics",
  "Cloud Computing, Big data, Distributed systems -- CSE EEE ECE",
  "Communication -- CSE EEE ECE",
  "Information Science and Systems -- CSE EEE ECE",
  "Biomedical Imaging, Sensing and Genomic Signal Processing -- CSE EEE ECE",
  "Product Development",
  "Product Design",
  "Digital marketing",
  "AI LLM based Product Dev",
  "Software development engineer",
  "Improv",
  "comedy",
  "YouTube",
  "video",
  "writing",
  "Cryptography -- CSE EEE ECE",
  "Industry standard certifications in the field of cyber security",
  "Culture Transformation",
  "Business Transformation",
  "Training & Development",
  "Capability Building",
  "Instructional design",
  "digital transformation",
  "Quality and regulatory audits for aircraft maintenance and MROs",
  "Green Energy-Solar power plants",
  "Energy and Power, Power Electronics -- CSE EEE ECE",
  "Analog and Mixed Signal -- CSE EEE ECE",
  "Digital VLSI -- CSE EEE ECE",
  "Automotive Industry in EV Powertain Development",
  "Telecommunication systems(SOFTWARE) -ECE EEE CSE",
  "Computer networks, security -- CSE EEE ECE",
  "Embedded Systems -- CSE EEE ECE",
  "Autonomous Driving -- CSE EEE ECE",
  "Platforms and Strategy",
  "Alliances and Go to Market",
  "Fund Raising",
  "Startups",
  "Digital transformation in Industrial context",
  "Petroleum/ Oil & Gas/ Petrochemical/ Mining engineering -- Mech Engg, Prod Engg",
  "Fluid mechanics and machinery -- Mech Engg, Prod Engg",
  "Mechatronics and robotics -- Mech Engg, Prod Engg",
  "Industrial Engineering -- Mech Engg, Prod Engg",
  "Supply Chain Management -- Mech Engg, Prod Engg",
  "Business Analytics -- Mech Engg, Prod Engg",
  "Therrmal Engineering -- Mech Engg, Prod Engg",
  "Transportation and Mobility -- Mech Engg, Prod Engg",
  "Machine design -- Mech Engg, Prod Engg",
  "Numerical Methods -- Mech Engg, Prod Engg",
  "Operations research -- Mech Engg, Prod Engg",
  "Operations Research & Optimization -- Mech Engg, Prod Engg",
  "Optimization -- Mech Engg, Prod Engg",
  "Behavioral Economics -- Mech Engg, Prod Engg",
  "Operations Engineering & Management -- Mech Engg, Prod Engg",
  "Manufacturing/Production Engineering -- Mech Engg, Prod Engg",
  "Clean energy -- Mech Engg, Prod Engg",
  "Quality & Reliability Engineering -- Mech Engg, Prod Engg",
  "Infrastructure Planning",
  "infrastructure finance",
  "Screenwriting",
  "entrepreneurship skills in film making",
  "Digital Marketing and Advertising",
  "Digital Marketing",
  "Graphic Designing",
  "Freelancing",
  "Automation and control",
  "Maintenance of Plant",
  "Heavy Machinery",
  "Marine engineering and merchant shipping -- Mech Engg, Prod Engg",
  "Creating professional resumes",
  "preparation for & cracking interviews",
  "finding good job opportunities",
  "drafting skills",
  "paper writings both in english and hindi",
  "Propulsion",
  "Cryogenics",
  "Robotics",
  "About marine engg and merchant shipping",
  "I have experience working in core as well as non-core fields",
  "More than specific expertise, I could help with thinking about different opportunities and how to best utilize time at NITC",
  "Aerospace systems performance",
  "autonomous driver assistance systems",
  "Organisational Change Management",
  "Organisational culture",
  "Upstream Oil & Gas (Exploration, Development & Production)",
  "Oil & Gas Markets",
  "Joint Venture & Stakeholder Management",
  "HSE",
  "40 years experience in import export, customs,logistics",
  "Supply chain management,sourcing and procurement",
  "Systematic Innovation and TRIZ",
  "Industrial design",
  "Frugal Innovation (Jugaad)",
  "Toys & Game Design",
  "Design for Education",
  "Ergonomics",
  "PRODUCT DESIGN",
  "User Research",
  "Consulting",
  "Mechanical asset integrity",
  "Industry 4.0",
  "industry consulting",
  "ERP",
  "Product Design - Mechanical engineering",
  "Intellectual Property",
  "Patenting",
  "Design of interactive learning environment",
  "40 years experience in import export, customs,logistics .Supply chain management,sourcing and procurement",
  "Creativity",
  "Computational physics and numerical methods -- Engg Phy",
  "Mathematical physics -- Mathematics",
  "Particle Physics",
  "Electromagnetics and Microwaves -- CSE EEE ECE",
  "Signals and Systems -- CSE EEE ECE",
  "Digital Signal Processing -- CSE EEE ECE",
  "SAP",
  "VLSI design",
  "front end",
  "VLSI verification",
  "Digital security for consumers / Telecom verticals",
  "Data Structures",
  "Algorithms",
  "Defence Services and Strategic Studies",
  "Nanoscale science and technology -- Engg Phy",
  "Materials for energy -- Engg Phy",
  "Electronics & Photonics -- Material Science",
  "Energy Production and Storage -- Material Science",
  "Bioinspired Materials and Systems -- Material Science",
  "Recycling of Aluminium",
  "UX Design",
  "UI design",
  "UX Research",
  "Deep learning",
  "Software Architecture",
  "building industry scale software tools in contrast to a college project",
  "coding standards",
  "setting up services and managing/monitoring Linux servers",
  "Programming languages and interview preparation",
  "Productivity / Limiting beliefs"
];

const test_areas = [
    "Auditing",
    "AutoCAD",
    "Automotive",
    "Art",
    "Analytical Skills",
    "Adobe Photoshop",
    "Art Direction",
    "Automation",
    "Adobe Illustrator",
    "Agile Methodologies",
    "Business Analysis",
    "Budgeting",
    "Business Strategy",
    "Business Process Improvement",
    "Business Services",
    "Business Planning",
    "Branding",
    "Business Intelligence",
    "Business Process",
    "Customer Service",
    "Communication",
    "Company Research",
    "Change Management",
    "Coaching",
    "Construction",
    "Customer Relationship Management",
    "Contractual Agreements",
    "Customer Satisfaction",
    "Contract Negotiation",
    "Design",
    "Databases",
    "Data Analysis",
    "Digital Marketing",
    "Decision Making",
    "Digital Media",
    "Drawing",
    "Development Tools",
    "Event Planning",
    "Editing",
    "Entrepreneurship",
    "Email",
    "Employee Benefits Design",
    "Energy",
    "Electronics",
    "Enterprise Software",
    "Ecommerce",
    "Finance",
    "Financial Analysis",
    "Fundraising",
    "Facility Management",
    "Food and Beverage",
    "Forecasting",
    "Facilitation",
    "Financial Risk",
    "Financial Reporting",
    "Government Agencies",
    "Grocery",
    "Graphic Design",
    "Gas",
    "Graphics",
    "Grant Writing",
    "General Ledger",
    "HTML",
    "Heavy Equipment",
    "Hospitals",
    "Higher Education",
    "History",
    "Healthcare",
    "Hospitality Industry",
    "Helping Clients Succeed",
    "Healthcare Management",
    "HTML5",
    "Information Technology",
    "Interpersonal Skills",
    "Information Systems",
    "Internal Audit",
    "Integration",
    "Insurance",
    "Investments",
    "Interviewing",
    "Invoicing",
    "Integrated Marketing",
    "Java",
    "Javascript",
    "JQuery",
    "Journalism",
    "Job Scanning",
    "Job Description Development",
    "Journals",
    "Joint Ventures",
    "Key Performance Indicators",
    "K12 Education",
    "Knowledge Management",
    "Kanban",
    "Key Account Development",
    "Knowledge Sharing",
    "Knowledge Base",
    "Kindergarten",
    "Leadership",
    "Logistics Management",
    "Local Marketing",
    "Legal Issues",
    "Linux",
    "Leadership Development",
    "Laboratory Skills",
    "Lean Manufacturing",
    "Litigation",
    "Legal Writing",
    "Negotiation",
    "Nonprofit Organizations",
    "New Business Opportunities",
    "Newsletters",
    "New Hires",
    "Network Communications",
    "Network Administration",
    "Network Systems",
    "Network Attached Storage",
    "Nutrition",
    "Order Fulfillment",
    "Online Advertising",
    "Operating Systems",
    "Organizational Development",
    "Operations Management",
    "Organizational Structure",
    "Office Administration",
    "Oracle Database",
    "Outsourcing",
    "Performance Tuning",
    "Public Speaking",
    "Project Planning",
    "Program Management",
    "Public Relations",
    "Public Policy",
    "Problem Solving",
    "Partnerships",
    "Presentations",
    "Pricing Strategy",
    "Qualitative Research",
    "Queues",
    "QuickBooks",
    "Quality System",
    "Quotations",
    "Quality Auditing",
    "Quantitative Research",
    "Qualifying Prospects",
    "Quality Improvement",
    "Query Writing",
    "Research",
    "Retail",
    "Recruiting",
    "Real Estate",
    "Reviews",
    "Requirements Analysis",
    "Range",
    "Regulations",
    "Residential Homes",
    "Records",
    "Strategic Planning",
    "Social Media",
    "Staff Development",
    "Sales Management",
    "Strategy",
    "Software",
    "Supervisory Skills",
    "SQL",
    "Software Documentation",
    "Schedules",
    "Training",
    "Teamwork",
    "Team Leadership",
    "Teaching",
    "Team Building",
    "Testing",
    "Time Management",
    "Team Management",
    "Troubleshooting",
    "Telecommunications",
    "Unix",
    "User Interface Design",
    "User Experience",
    "Underwriting",
    "Department of Defense",
    "Unified Modeling Language",
    "University Teaching",
    "User Acceptance Testing",
    "Vendor Management",
    "Video",
    "Video Production",
    "Volunteering",
    "Validation",
    "Vendors",
    "Volunteer Management",
    "Video Editing",
    "Visual Merchandising",
    "Windows",
    "Writing",
    "Web Design",
    "Web Development",
    "Windows Server",
    "Workshops",
    "Web Applications",
    "Water Resource Management",
    "WordPress",
    "Wireless Technologies",
    "Marine Corps",
    "Medical Compliance",
    "Military Aviation",
    "Military Weapons",
    "Mechanical Engineering",
    "Basketball",
    "Football",
    "Baseball",
    "Swimming",
    "Volleyball",
    "Soccer",
    "Gymnastics",
    "Golf",
    "Diving"
];

module.exports = {broad_areas, narrow_areas, test_areas};